/** Field clauses: nullability, identity, default, CHECK, generated/computed, comment. */
import { defineTable, s, sqlExpr } from "../../src/authoring";
import type { ExampleGroup } from "./_kit";

export const group: ExampleGroup = {
  file: "03-field-clauses.ts",
  about:
    "Field clauses — nullability, identity, default, check, generated, comment",
  examples: [
    {
      title: "nullability (.optional / .nullable both -> a nullable column)",
      defs: [
        defineTable("t", {
          age: s.smallint().optional(),
          bio: s.text().nullable(),
        }),
      ],
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "age" smallint,
  "bio" text
);`,
    },
    {
      title: "identity column (GENERATED ... AS IDENTITY)",
      defs: [defineTable("t", { seq: s.integer().$identity("by-default") })],
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "seq" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
);`,
    },
    {
      title: "default: a JS literal vs sqlExpr() for a SQL expression",
      note: "$default needs sqlExpr() to tell a SQL expr from a literal; emit-faithful, excluded from drift",
      defs: [
        defineTable("t", {
          status: s.text().$default("active"),
          created: s.timestamptz().$default(sqlExpr("now()")),
        }),
      ],
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT now(),
  "status" text NOT NULL DEFAULT 'active'
);`,
    },
    {
      title: "field CHECK (a bare string expression)",
      defs: [defineTable("t", { score: s.integer().$check("score >= 0") })],
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "score" integer NOT NULL CHECK (score >= 0)
);`,
    },
    {
      title: "generated / computed column (STORED)",
      note: 'reference other columns by their (quoted) name; camelCase needs quotes: "unitPrice"',
      defs: [
        defineTable("line", {
          quantity: s.integer(),
          unitPrice: s.numeric(10, 2),
          total: s.numeric(12, 2).$generated('quantity * "unitPrice"'),
        }),
      ],
      ddl: `CREATE TABLE "line" (
  "id" text PRIMARY KEY,
  "quantity" integer NOT NULL,
  "total" numeric(12, 2) NOT NULL GENERATED ALWAYS AS (quantity * "unitPrice") STORED,
  "unitPrice" numeric(10, 2) NOT NULL
);`,
    },
    {
      title: "column comment (COMMENT ON COLUMN)",
      note: "emit-only — not introspected back yet",
      defs: [defineTable("t", { note: s.text().$comment("free text") })],
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "note" text NOT NULL
);
COMMENT ON COLUMN "t"."note" IS 'free text';`,
    },
  ],
};
