/** Field clauses: nullability, identity, default, CHECK, generated/computed, comment. */
import { type ExampleGroup, example } from "./_kit";

export const group: ExampleGroup = {
  file: "03-field-clauses.ts",
  about:
    "Field clauses — nullability, identity, default, check, generated, comment",
  examples: [
    example({
      title: "nullability (.optional / .nullable both -> a nullable column)",
      code: `defineTable("t", { age: s.smallint().optional(), bio: s.text().nullable() })`,
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "age" smallint,
  "bio" text
);`,
    }),
    example({
      title: "identity column (GENERATED ... AS IDENTITY)",
      code: `defineTable("t", { seq: s.integer().$identity("by-default") })`,
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "seq" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
);`,
    }),
    example({
      title: "default: a JS literal vs sqlExpr() for a SQL expression",
      note: "$default needs sqlExpr() to tell a SQL expr from a literal; emit-faithful, excluded from drift",
      code: `defineTable("t", {
  status: s.text().$default("active"),
  created: s.timestamptz().$default(sqlExpr("now()")),
})`,
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT now(),
  "status" text NOT NULL DEFAULT 'active'
);`,
    }),
    example({
      title: "field CHECK (a bare string expression)",
      code: `defineTable("t", { score: s.integer().$check("score >= 0") })`,
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "score" integer NOT NULL CHECK (score >= 0)
);`,
    }),
    example({
      title: "generated / computed column (STORED)",
      note: 'reference other columns by their (quoted) name; camelCase needs quotes: "unitPrice"',
      code: `defineTable("line", {
  quantity: s.integer(),
  unitPrice: s.numeric(10, 2),
  total: s.numeric(12, 2).$generated('quantity * "unitPrice"'),
})`,
      ddl: `CREATE TABLE "line" (
  "id" text PRIMARY KEY,
  "quantity" integer NOT NULL,
  "total" numeric(12, 2) NOT NULL GENERATED ALWAYS AS (quantity * "unitPrice") STORED,
  "unitPrice" numeric(10, 2) NOT NULL
);`,
    }),
    example({
      title: "column comment (COMMENT ON COLUMN)",
      note: "emit-only — not introspected back yet",
      code: `defineTable("t", { note: s.text().$comment("free text") })`,
      ddl: `CREATE TABLE "t" (
  "id" text PRIMARY KEY,
  "note" text NOT NULL
);
COMMENT ON COLUMN "t"."note" IS 'free text';`,
    }),
  ],
};
