/**
 * Admin migration script — run as root.
 *
 *   bun run setup        # uses SURREAL_* from .env
 *
 * What it does:
 *   1. DEFINE NAMESPACE / DATABASE.
 *   2. Apply table + field DDL generated by surreal-zod (`emitTable`). This now
 *      includes per-table row-level `PERMISSIONS`, authored in `src/schema.ts` via
 *      `.permissions({...})` and folded into the single `DEFINE TABLE` — so a
 *      signed-in user only touches their own data.
 *   3. Raw SurrealQL the package does NOT generate yet (until the ORM lands):
 *        - a unique email index,
 *        - `DEFINE ACCESS ... TYPE RECORD` with SIGNUP / SIGNIN.
 *
 * The internal `passhash` field (TYPE string PERMISSIONS NONE) is generated by
 * `defineTable` from `User`'s `.$internal()` field — no longer hand-written here.
 *
 * `migrate()` is exported so the integration tests can reuse it against a scratch DB.
 */
import { Surreal } from "surrealdb";
import { emitTable } from "surreal-zod";
import { DB } from "./src/db";
import { tables } from "./src/schema";

/** Step 2 + the internal bits of step 3: schema (incl. `passhash` + row-level
 * permissions), unique index. */
export async function applySchema(db: Surreal): Promise<void> {
  const ddl = tables.map((t) => emitTable(t, { exists: "overwrite" })).join("\n");
  await db.query(ddl);
  // `passhash` rides in the generated DDL as a `.$internal()` field (TYPE string
  // PERMISSIONS NONE) — hidden from the app type yet present so SCHEMAFULL SIGNUP writes.
  // Per-table row-level PERMISSIONS now ride in the same generated `DEFINE TABLE` too,
  // authored as `.permissions({...})` in `src/schema.ts`.
  await db.query(`
    DEFINE INDEX OVERWRITE email_unique ON TABLE user FIELDS email UNIQUE;
  `);
}

/** Record access: end users sign up / sign in directly (used by the browser app). */
export async function applyAccess(db: Surreal, access = DB.access): Promise<void> {
  await db.query(`
    DEFINE ACCESS OVERWRITE ${access} ON DATABASE TYPE RECORD
      SIGNUP {
        RETURN CREATE user CONTENT {
          name: $name,
          email: $email,
          passhash: crypto::argon2::generate($pass)
        };
      }
      SIGNIN {
        LET $user = SELECT * FROM ONLY user WHERE email = $email LIMIT 1;
        IF $user.id != NONE AND crypto::argon2::compare($user.passhash, $pass) {
          RETURN $user
        } ELSE {
          THROW "Invalid email or password"
        };
      }
      DURATION FOR TOKEN 1h, FOR SESSION 12h;
  `);
}

/** The full migration (schema incl. permissions + record access). Assumes ns/db are selected. */
export async function migrate(db: Surreal): Promise<void> {
  await applySchema(db);
  await applyAccess(db);
}

async function main(): Promise<void> {
  const user = process.env.SURREAL_USER;
  const pass = process.env.SURREAL_PASS;
  if (!user || !pass) {
    throw new Error("Set SURREAL_USER / SURREAL_PASS in .env (root credentials) to run setup.");
  }

  const db = new Surreal();
  await db.connect(DB.url);
  await db.signin({ username: user, password: pass });
  await db.query(`DEFINE NAMESPACE IF NOT EXISTS \`${DB.namespace}\`;`);
  await db.use({ namespace: DB.namespace });
  await db.query(`DEFINE DATABASE IF NOT EXISTS \`${DB.database}\`;`);
  await db.use({ namespace: DB.namespace, database: DB.database });

  await migrate(db);

  console.log(`Migrated ns="${DB.namespace}" db="${DB.database}"`);
  console.log(`  tables/relations: ${tables.map((t) => t.name).join(", ")}`);
  console.log(`  record access:    "${DB.access}" (SIGNUP / SIGNIN)`);
  console.log("  row-level PERMISSIONS generated from the schema (.permissions).");
  await db.close();
}

if (import.meta.main) {
  await main();
}
