/**
 * Admin migration script — run as root.
 *
 *   bun run setup        # uses SURREAL_* from .env
 *
 * What it does:
 *   1. DEFINE NAMESPACE / DATABASE.
 *   2. Apply table + field DDL generated by @schemic/core (`emitTable`). This now
 *      includes per-table row-level `PERMISSIONS`, authored in `src/schema.ts` via
 *      `.permissions({...})` and folded into the single `DEFINE TABLE` — so a
 *      signed-in user only touches their own data. The unique email index and a
 *      `task` "stamp completedAt" event are also generated from `src/schema.ts`.
 *   3. Apply the record `DEFINE ACCESS` (SIGNUP / SIGNIN) — also authored in
 *      `src/schema.ts` as the `account` `defineAccess(...)` and emitted here from
 *      that single source.
 *
 * Everything this script writes is now generated from `src/schema.ts`; there is no
 * hand-written SurrealQL left. The internal `passhash` field (TYPE string PERMISSIONS
 * NONE) is generated by `defineTable` from `User`'s `.$internal()` field.
 *
 * `migrate()` is exported so the integration tests can reuse it against a scratch DB.
 */
import { Surreal } from "surrealdb";
import { emitDefStatement, emitTable } from "@schemic/surreal";
import { DB } from "./src/db";
import { account, tables } from "./src/schema";

/** Step 2: schema DDL generated by @schemic/core (incl. `passhash` + row-level
 * permissions + the unique email index). */
export async function applySchema(db: Surreal): Promise<void> {
  const ddl = tables.map((t) => emitTable(t, { exists: "overwrite" })).join("\n");
  await db.query(ddl);
  // `passhash` rides in the generated DDL as a `.$internal()` field (TYPE string
  // PERMISSIONS NONE) — hidden from the app type yet present so SCHEMAFULL SIGNUP writes.
  // Per-table row-level PERMISSIONS now ride in the same generated `DEFINE TABLE` too,
  // authored as `.permissions({...})` in `src/schema.ts`. The unique email index also
  // rides along, generated from `email: s.email().unique()` (as `user_email_idx`).
}

/**
 * Record access: end users sign up / sign in directly (used by the browser app). The
 * `DEFINE ACCESS` now lives in `src/schema.ts` as the `account` `defineAccess(...)`; we
 * emit it from that single source here (with `OVERWRITE` so re-runs are idempotent).
 */
export async function applyAccess(db: Surreal): Promise<void> {
  const { ddl } = emitDefStatement(account, { exists: "overwrite" });
  await db.query(ddl);
}

/** The full migration (schema incl. permissions + record access). Assumes ns/db are selected. */
export async function migrate(db: Surreal): Promise<void> {
  await applySchema(db);
  await applyAccess(db);
}

async function main(): Promise<void> {
  const user = process.env.SURREAL_USER;
  const pass = process.env.SURREAL_PASS;
  if (!user || !pass) {
    throw new Error("Set SURREAL_USER / SURREAL_PASS in .env (root credentials) to run setup.");
  }

  const db = new Surreal();
  await db.connect(DB.url);
  await db.signin({ username: user, password: pass });
  await db.query(`DEFINE NAMESPACE IF NOT EXISTS \`${DB.namespace}\`;`);
  await db.use({ namespace: DB.namespace });
  await db.query(`DEFINE DATABASE IF NOT EXISTS \`${DB.database}\`;`);
  await db.use({ namespace: DB.namespace, database: DB.database });

  await migrate(db);

  console.log(`Migrated ns="${DB.namespace}" db="${DB.database}"`);
  console.log(`  tables/relations: ${tables.map((t) => t.name).join(", ")}`);
  console.log(`  record access:    "${DB.access}" (SIGNUP / SIGNIN)`);
  console.log("  row-level PERMISSIONS generated from the schema (.permissions).");
  await db.close();
}

if (import.meta.main) {
  await main();
}
