/**
 * Admin migration script — run as root.
 *
 *   bun run setup        # uses SURREAL_* from .env
 *
 * What it does:
 *   1. DEFINE NAMESPACE / DATABASE.
 *   2. Apply table + field DDL generated by surreal-zod (`defineTable`).
 *   3. Raw SurrealQL the package does NOT generate (see DX-FINDINGS.md):
 *        - the internal `passhash` field (PERMISSIONS NONE) + a unique email index,
 *        - `DEFINE ACCESS ... TYPE RECORD` with SIGNUP / SIGNIN,
 *        - per-table `PERMISSIONS` so a signed-in user only touches their own data.
 *
 * `migrate()` is exported so the integration tests can reuse it against a scratch DB.
 */
import { Surreal } from "surrealdb";
import { defineTable } from "surreal-zod";
import { DB } from "./src/db";
import { tables } from "./src/schema";

/** Step 2 + the internal bits of step 3: schema, secret field, unique index. */
export async function applySchema(db: Surreal): Promise<void> {
  const ddl = tables.map((t) => defineTable(t, { exists: "overwrite" })).join("\n");
  await db.query(ddl);
  // `passhash` is deliberately absent from the shared schema (it must never appear
  // in the app type), so it is defined here. PERMISSIONS NONE hides it from clients.
  await db.query(`
    DEFINE FIELD OVERWRITE passhash ON TABLE user TYPE string PERMISSIONS NONE;
    DEFINE INDEX OVERWRITE email_unique ON TABLE user FIELDS email UNIQUE;
  `);
}

/** Record access: end users sign up / sign in directly (used by the browser app). */
export async function applyAccess(db: Surreal, access = DB.access): Promise<void> {
  await db.query(`
    DEFINE ACCESS OVERWRITE ${access} ON DATABASE TYPE RECORD
      SIGNUP {
        RETURN CREATE user CONTENT {
          name: $name,
          email: $email,
          passhash: crypto::argon2::generate($pass)
        };
      }
      SIGNIN {
        LET $user = SELECT * FROM ONLY user WHERE email = $email LIMIT 1;
        IF $user.id != NONE AND crypto::argon2::compare($user.passhash, $pass) {
          RETURN $user
        } ELSE {
          THROW "Invalid email or password"
        };
      }
      DURATION FOR TOKEN 1h, FOR SESSION 12h;
  `);
}

/**
 * Per-table row-level permissions for record users. The package does not generate
 * these, so each table is re-declared with `DEFINE TABLE OVERWRITE` (note: this
 * also re-states TYPE/SCHEMAFULL/COMMENT — see DX-FINDINGS.md).
 */
export async function applyPermissions(db: Surreal): Promise<void> {
  // Visibility of a project: owner, public, or a member.
  const projectVisible = `owner = $auth.id OR settings.isPublic = true OR id IN $auth->member->project`;
  // Visibility of a task/comment derives from its project.
  const taskVisible = `project.owner = $auth.id OR project.settings.isPublic = true OR project IN $auth->member->project`;
  const taskWritable = `project.owner = $auth.id OR project IN $auth->member->project`;
  const commentVisible = `task.project.owner = $auth.id OR task.project.settings.isPublic = true OR task.project IN $auth->member->project`;

  await db.query(`
    DEFINE TABLE OVERWRITE user TYPE NORMAL SCHEMAFULL COMMENT "Application end users"
      PERMISSIONS
        FOR select WHERE $auth.id != NONE
        FOR create NONE
        FOR update, delete WHERE id = $auth.id;

    DEFINE TABLE OVERWRITE project TYPE NORMAL SCHEMAFULL COMMENT "Project workspaces"
      PERMISSIONS
        FOR select WHERE ${projectVisible}
        FOR create WHERE owner = $auth.id
        FOR update, delete WHERE owner = $auth.id;

    DEFINE TABLE OVERWRITE task TYPE NORMAL SCHEMAFULL COMMENT "Project tasks"
      PERMISSIONS
        FOR select WHERE ${taskVisible}
        FOR create, update, delete WHERE ${taskWritable};

    DEFINE TABLE OVERWRITE comment TYPE NORMAL SCHEMAFULL COMMENT "Task comments"
      PERMISSIONS
        FOR select WHERE ${commentVisible}
        FOR create WHERE ${commentVisible}
        FOR update, delete WHERE author = $auth.id;

    DEFINE TABLE OVERWRITE member TYPE RELATION FROM user TO project SCHEMAFULL
      PERMISSIONS
        FOR select WHERE in = $auth.id OR out.owner = $auth.id
        FOR create, update WHERE out.owner = $auth.id
        FOR delete WHERE out.owner = $auth.id OR in = $auth.id;

    DEFINE TABLE OVERWRITE watch TYPE RELATION FROM user TO task SCHEMAFULL
      PERMISSIONS
        FOR select, create, delete WHERE in = $auth.id;

    DEFINE TABLE OVERWRITE depends_on TYPE RELATION FROM task TO task SCHEMAFULL
      PERMISSIONS
        FOR select, create, delete
        WHERE in.project.owner = $auth.id OR in.project IN $auth->member->project;
  `);
}

/** The full migration (schema + access + permissions). Assumes ns/db are selected. */
export async function migrate(db: Surreal): Promise<void> {
  await applySchema(db);
  await applyAccess(db);
  await applyPermissions(db);
}

async function main(): Promise<void> {
  const user = process.env.SURREAL_USER;
  const pass = process.env.SURREAL_PASS;
  if (!user || !pass) {
    throw new Error("Set SURREAL_USER / SURREAL_PASS in .env (root credentials) to run setup.");
  }

  const db = new Surreal();
  await db.connect(DB.url);
  await db.signin({ username: user, password: pass });
  await db.query(`DEFINE NAMESPACE IF NOT EXISTS \`${DB.namespace}\`;`);
  await db.use({ namespace: DB.namespace });
  await db.query(`DEFINE DATABASE IF NOT EXISTS \`${DB.database}\`;`);
  await db.use({ namespace: DB.namespace, database: DB.database });

  await migrate(db);

  console.log(`Migrated ns="${DB.namespace}" db="${DB.database}"`);
  console.log(`  tables/relations: ${tables.map((t) => t.name).join(", ")}`);
  console.log(`  record access:    "${DB.access}" (SIGNUP / SIGNIN)`);
  console.log("  row-level PERMISSIONS applied for all tables.");
  await db.close();
}

if (import.meta.main) {
  await main();
}
