import { describe, expect, test } from "bun:test";
import {
  defineTable,
  type PgConn,
  postgresDriver,
  s,
  sqlExpr,
} from "../src/index";

// The pg-native s.* authoring surface: author with pg vocabulary -> lower to the portable IR ->
// emit pg DDL -> apply to a real PGlite -> introspect -> diff = 0. Structural clauses (native types
// + params, identity, composite PK, FK actions) round-trip; expression clauses (default/check/
// generated/comment) are emit-faithful but excluded from equality (Postgres rewrites them).

const lower = (...tables: ReturnType<typeof defineTable>[]) =>
  postgresDriver.lower(tables, []);

async function open(): Promise<PgConn> {
  return (await postgresDriver.connect({
    params: { url: "" },
  } as never)) as PgConn;
}

describe("lower: pg s.* -> portable IR", () => {
  test("canonical types -> portable scalars; pg-specific -> native(+params)", () => {
    const t = defineTable("widget", {
      name: s.text(),
      count: s.integer(),
      big: s.bigint(),
      price: s.numeric(12, 2),
      label: s.varchar(255),
      created: s.timestamptz(),
      tags: s.text().array(),
      meta: s.jsonb(),
    });
    const { tables } = lower(t);
    const f = new Map(tables[0].fields.map((x) => [x.name, x.type]));
    expect(f.get("name")).toEqual({ t: "scalar", name: "string" });
    expect(f.get("count")).toEqual({ t: "scalar", name: "int" });
    expect(f.get("big")).toEqual({
      t: "native",
      db: "postgres",
      name: "bigint",
    });
    expect(f.get("price")).toEqual({
      t: "native",
      db: "postgres",
      name: "numeric",
      params: [12, 2],
    });
    expect(f.get("label")).toEqual({
      t: "native",
      db: "postgres",
      name: "varchar",
      params: [255],
    });
    expect(f.get("created")).toEqual({ t: "scalar", name: "datetime" });
    expect(f.get("tags")).toEqual({
      t: "array",
      elem: { t: "scalar", name: "string" },
    });
    expect(f.get("meta")).toEqual({ t: "object", fields: {} });
  });

  test("optional/nullable wrappers + clauses land in the IR", () => {
    const t = defineTable("acct", {
      age: s.smallint().optional(),
      seq: s.integer().$identity("always"),
      who: s.references("person", {
        onDelete: "cascade",
        onUpdate: "restrict",
      }),
    });
    const byName = new Map(lower(t).tables[0].fields.map((x) => [x.name, x]));
    expect(byName.get("age")?.type).toEqual({
      t: "option",
      inner: { t: "native", db: "postgres", name: "smallint" },
    });
    expect(byName.get("seq")?.identity).toBe("always");
    expect(byName.get("who")?.type).toEqual({
      t: "record",
      tables: ["person"],
    });
    expect(byName.get("who")?.reference).toEqual({
      on_delete: "cascade",
      on_update: "restrict",
    });
  });

  test("table-level composite PK + field clauses", () => {
    const t = defineTable("member", {
      org: s.text(),
      person: s.text(),
      role: s.text().$default("member"),
      score: s.integer().$check("score >= 0"),
    }).primaryKey("org", "person");
    const tbl = lower(t).tables[0];
    expect(tbl.primaryKey).toEqual(["org", "person"]);
    const byName = new Map(tbl.fields.map((x) => [x.name, x]));
    expect(byName.get("role")?.default).toBe("'member'");
    expect(byName.get("score")?.check).toBe("score >= 0");
  });
});

describe("emit: DDL clause rendering", () => {
  const ddl = (t: ReturnType<typeof defineTable>) =>
    postgresDriver
      .emit(lower(t))
      .map((x) => x.ddl)
      .join("\n");

  test("native types with params, identity, default, check, generated", () => {
    const out = ddl(
      defineTable("p", {
        label: s.varchar(255),
        price: s.numeric(10, 2),
        seq: s.integer().$identity("by-default"),
        status: s.text().$default("active"),
        created: s.timestamptz().$default(sqlExpr("now()")),
        score: s.integer().$check("score >= 0"),
        total: s.numeric(12, 2).$generated("price * 2"),
        note: s.text().$comment("free text"),
      }),
    );
    expect(out).toContain('"label" varchar(255)');
    expect(out).toContain('"price" numeric(10, 2)');
    expect(out).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(out).toContain("DEFAULT 'active'");
    expect(out).toContain("DEFAULT now()");
    expect(out).toContain("CHECK (score >= 0)");
    expect(out).toContain("GENERATED ALWAYS AS (price * 2) STORED");
    expect(out).toContain('COMMENT ON COLUMN "p"."note" IS \'free text\'');
  });

  test("composite PK replaces the implicit id; FK carries ON DELETE/UPDATE", () => {
    const member = ddl(
      defineTable("m", { a: s.text(), b: s.text() }).primaryKey("a", "b"),
    );
    expect(member).toContain('PRIMARY KEY ("a", "b")');
    expect(member).not.toContain('"id" text PRIMARY KEY');

    const post = ddl(
      defineTable("post", {
        author: s.references("usr", {
          onDelete: "cascade",
          onUpdate: "no action",
        }),
      }),
    );
    expect(post).toContain("ON DELETE cascade");
    expect(post).toContain("ON UPDATE no action");
  });

  test("$unique emits a UNIQUE index", () => {
    const out = ddl(defineTable("u", { email: s.text().$unique() }));
    expect(out).toContain('CREATE UNIQUE INDEX "u_email_key" ON "u" ("email")');
  });
});

describe("round-trip: author -> emit -> PGlite -> introspect -> diff = 0", () => {
  test("diverse native types + nullability + identity", async () => {
    const widget = defineTable("widget", {
      name: s.varchar(255),
      age: s.smallint().optional(),
      balance: s.numeric(12, 2),
      big: s.bigint(),
      ratio: s.real(),
      active: s.boolean(),
      created: s.timestamptz(),
      meta: s.jsonb(),
      tags: s.text().array(),
      token: s.uuid(),
      seq: s.integer().$identity("by-default"),
    });
    const ir = lower(widget);
    const conn = await open();
    try {
      await postgresDriver.apply(
        conn,
        postgresDriver.emit(ir).map((x) => x.ddl),
      );
      const live = await postgresDriver.introspect(conn);
      expect(postgresDriver.equal(ir, live)).toBe(true);
    } finally {
      await conn.close();
    }
  });

  test("FK with referential actions + composite PK", async () => {
    const user = defineTable("user", { name: s.text() });
    const post = defineTable("post", {
      title: s.text(),
      author: s.references("user", { onDelete: "cascade" }),
    });
    const member = defineTable("member", {
      org: s.text(),
      person: s.text(),
    }).primaryKey("org", "person");

    const ir = lower(user, post, member);
    const conn = await open();
    try {
      await postgresDriver.apply(
        conn,
        postgresDriver.emit(ir).map((x) => x.ddl),
      );
      const live = await postgresDriver.introspect(conn);
      expect(postgresDriver.equal(ir, live)).toBe(true);
    } finally {
      await conn.close();
    }
  });

  test("$postgres escape hatch round-trips as its native pg type", async () => {
    const codec = s.$postgres(
      "text",
      // an App-side object stored as text via a Zod codec
      s.text().schema,
    );
    const t = defineTable("blob", { raw: codec });
    const ir = lower(t);
    const conn = await open();
    try {
      await postgresDriver.apply(
        conn,
        postgresDriver.emit(ir).map((x) => x.ddl),
      );
      const live = await postgresDriver.introspect(conn);
      expect(postgresDriver.equal(ir, live)).toBe(true);
    } finally {
      await conn.close();
    }
  });
});
